Refactor templates
ambient-innovation/ambient-package-update pull request #9
Opened 2024-06-15 10:01 UTC by fbinz

I adjusted template rendering, so that users can define their own templates.
The main usage for now is the README.md, where packages can now specify their own snippets in their `.ambient-package-update/template/snippets` directory.

2024-06-15 10:06 UTC, fbinz commented
You can see how to the new metadata properties can be used here: [Link](https://github.com/fbinz/django-lucide-icons/commit/a59891ce7ba16e57ab4469ab5c93248a7904b3c6#diff-e59a03d06a0682050a193c3a970de8b71d17eb2d1882dbbe780810d2bdd10e65R26)

2024-06-19 12:14 UTC, GitRon requested changes
Great work in total! Seems like an amazing improvement!

2024-06-19 12:14 UTC, GitRon commented on ambient_package_update/cli.py
> +    j2_template = env.get_template(str(template))
@fbinz can we keep this somehow? `keep_trailing_newline=True`

2024-06-19 12:14 UTC, GitRon commented on ambient_package_update/templates/snippets/contribute.tpl
> +{% endif %}
@fbinz To avoid git changes from the IDE, I prefer newlines at the end of the template files

2024-06-19 12:25 UTC, fbinz commented on ambient_package_update/templates/snippets/contribute.tpl
> +{% endif %}
Done :)

2024-06-19 12:26 UTC, fbinz commented on ambient_package_update/cli.py
> +    j2_template = env.get_template(str(template))
Ah, seems like it can be configured on the Environment instance.

2024-06-19 12:27 UTC, GitRon commented on ambient_package_update/cli.py
> +    j2_template = env.get_template(str(template))
👌

2024-06-19 12:27 UTC, GitRon commented on ambient_package_update/templates/snippets/contribute.tpl
> +{% endif %}
❤️

2024-06-19 15:06 UTC, GitRon commented
@fbinz I get an error while running the CLI command:

> jinja2.exceptions.TemplateNotFound: .github\workflows\ci.yml.tpl

Both of us didn't change that one so it's not a super obvious one. Can you reproduce the issue?

2024-06-19 15:10 UTC, fbinz commented
> @fbinz I get an error while running the CLI command:
> 
> > jinja2.exceptions.TemplateNotFound: .github\workflows\ci.yml.tpl
> 
> Both of us didn't change that one so it's not a super obvious one. Can you reproduce the issue?

Interesting. Will try to reproduce it later this evening!

2024-06-19 17:18 UTC, fbinz commented
@GitRon 
I cannot reproduce this issue. How did you install the development version locally? 
I did: `pip install -e ../ambient-package-update` to test my changes in my "django-lucide-icons" repository.

2024-06-20 06:28 UTC, GitRon commented on ambient_package_update/cli.py
> +    j2_template = env.get_template(str(template))
```suggestion
    j2_template = env.get_template(str(template).replace("\\", "/"))
```

Windows issue 🙃

2024-06-20 06:33 UTC, GitRon commented on ambient_package_update/metadata/readme.py
>      custom_installation: Optional[str] = None
@fbinz In your other PR, you're using `content_template`, this variable doesn't seem to have any effect anymore. What's the way to go here? Keep this attribute for downwards compat or remove it and create a new template for custom content?

2024-06-20 06:33 UTC, GitRon requested changes
Two minor issues left 🙂

2024-06-20 09:03 UTC, fbinz commented on ambient_package_update/metadata/readme.py
>      custom_installation: Optional[str] = None
Ah, I see what you mean. I'm using `content_template` [here](https://github.com/ambient-innovation/ambient-package-update/pull/9/files#diff-587653731974bed31a74eff07fb63fd2c30c6d104e0340d38c2880675c370f10R5), so that users just need to set the `content_template` and not overwrite the whole `README.md.tpl`.

2024-06-20 09:03 UTC, fbinz commented on ambient_package_update/cli.py
> +    j2_template = env.get_template(str(template))
Fixed :)

2024-06-20 11:19 UTC, GitRon commented on ambient_package_update/metadata/readme.py
>      custom_installation: Optional[str] = None
nice 👌

2024-06-20 11:19 UTC, GitRon commented on ambient_package_update/templates/snippets/tagline.tpl
> +{{ readme_content.tagline }}
```suggestion
{{ readme_content.tagline }}

```

2024-06-20 11:19 UTC, GitRon commented on ambient_package_update/templates/snippets/content.tpl
> +{{ readme_content.content }}
```suggestion
{{ readme_content.content }}

```

2024-06-20 11:20 UTC, GitRon commented on ambient_package_update/templates/README.md.tpl
> +{% include "snippets/maintenance.tpl" %}
```suggestion
{% include "snippets/maintenance.tpl" %}

```

2024-06-20 11:26 UTC, GitRon commented on ambient_package_update/metadata/readme.py
>      tagline: str
```suggestion
    tagline: str = None
```

2024-06-20 13:47 UTC, GitRon approved these changes

2024-06-20 13:48 UTC, merged